name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install project dependencies
        run: npm install    

      - name: Install dotenv
        run: npm install dotenv


      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            CYPRESS_FIRSTNAME: ${{ secrets.firstname }}
            CYPRESS_LASTNAME: ${{ secrets.lastName }}
            CYPRESS_POSTALCODE: ${{ secrets.postalCode }}
