name: Run Tests

on:
    push:
        branches:
            - '**'

    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install project dependencies
        run: npm install    

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            CYPRESS_FIRSTNAME: ${{ secrets.firstname }}
            CYPRESS_LASTNAME: ${{ secrets.lastName }}
            CYPRESS_POSTALCODE: ${{ secrets.postalCode }}
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.cypress-testing-step.outcome == 'failure' }}
        with:
            name: cypress-screenshots
            path: ./tests/cypress/screenshots
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.cypress-testing-step.outcome == 'failure' }}
        with:
            name: cypress-videos
            path: ./tests/cypress/videos
            if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.cypress-testing-step.outcome == 'failure' }}
        with:
              name: cypress-logs
              path: ./tests/cypress/logs
              if-no-files-found: ignore
